### ISSUE TITLE
Migrate tests to `@playwright/test`

### ISSUE THREAD

**Issue by mskelton** [playwright-community/expect-playwright#103]
Unrelated to this PR. I'm thinking if we should either use [resetContext](https://github.com/playwright-community/jest-playwright#reset-current-context) every where or easier migrate to the Playwright Test runner and keep an integration test for the Jest preset.

_Originally posted by @mxschmitt in https://github.com/playwright-community/expect-playwright/issues/102#issuecomment-869162636_

**Comment by mxschmitt** [comment]
I'm not sure about code coverage, thats something which is not supported in playwright-test.

**Comment by mskelton** [comment]
@mxschmitt So, do we want to close this since you merged #110?
