### ISSUE TITLE
expect-playwright not working with jest-playwright

### ISSUE THREAD

**Issue by michal-radziwilko** [playwright-community/expect-playwright#126]
While trying out jest-playwright i've experienced issue with expect-playwright. My project [GitHub repo](https://github.com/michal-radziwilko/jest-playwright). I cannot use any assertions from expect-playwright, when running tests from terminal the following error occurs:

    TypeError: expect(...).toHaveTitle is not a function

      1 | export async function testGoogle(){
      2 |     await page.screenshot({path: './target/sampleTest/sampleTest.png'})
    > 3 |     await expect(page).toHaveTitle('Google');
        |                        ^
      4 | }

      at Object.testGoogle (src/util/sampleTest.js:3:24)
      at Object.<anonymous> (src/spec/sample.spec.js:8:5)

**Comment by nowrap** [comment]
This also happens for toHaveURL()

**Comment by mxschmitt** [comment]
There is no toHaveTitle matcher in expect-playwright. Its called [toMatchTitle](https://github.com/playwright-community/expect-playwright#toMatchTitle)
