### ISSUE TITLE
Error: `elementHandle.waitForSelector` is not a function

### ISSUE THREAD

**Issue by marekdedic** [playwright-community/expect-playwright#127]
Hi,
I tried to follow the `jest-playwritght` basic example, so the following test:

```ts
test("TEST", async () => {
  await page.goto("https://playwright.dev/");
  const title = page.locator(".navbar__inner .navbar__title");
  await expect(title).toHaveText("Playwright");
})
```

However, I got `Error: Timeout exceed for element 'body'`. I followed the error message to [here](https://github.com/playwright-community/expect-playwright/blob/master/src/matchers/utils.ts#L58-L62), commented out the try-catch (leaving the body of course) and I got `TypeError: elementHandle.waitForSelector is not a function` - which I don't know how to solve.

At the line in question, I listed the following variables for context:
`args`: `[ Locator@.navbar__inner .navbar__title ]`
`elementHandle`: `Locator@.navbar__inner .navbar__title`
`elementHandle.waitForSelector`: `undefined`
`console.trace()`:
```
Trace:
        at Object.getElementHandle (/home/user/project/node_modules/expect-playwright/lib/matchers/utils.js:32:21)
        at runNextTicks (internal/process/task_queues.js:60:5)
        at processImmediate (internal/timers.js:437:9)
        at Object.toHaveText (/home/user/project/node_modules/expect-playwright/lib/matchers/toHaveText/index.js:10:50)
```

**Comment by mskelton** [comment]
What version of expect-playwright are you using?

**Comment by marekdedic** [comment]
I am on `0.7.2` (as a transitive dependency of `jest-playwright-preset`)

**Comment by mskelton** [comment]
Gotcha, expect-playwright 0.8.0 is required when using locators.  All that to say, is there a reason you are unable to [Playwright test](https://playwright.dev/docs/intro)?  Playwright test is the official test runner and recommended in place of expect playwright and jest playwright.

**Comment by marekdedic** [comment]
Well then the `jest-playwright` readme is out of sync with its dependencies...

As for why use it - I'm already running my backend tests in jest, so it seemed simpler to just use the same runner...
