### ISSUE TITLE
Question: Is this still a recommended library for integration tests?

### ISSUE THREAD

**Issue by williamlabrum** [playwright-community/expect-playwright#133]
Just wondering if this library is still a suggested library to use for integration testing (or otherwise) over the Playwright API provided currently (1.46.0)? It seems like this is still supported but hasn't been updated for some years suggesting it may be obsolete to the current playwright api. @mxschmitt

**Comment by mxschmitt** [comment]
This library originated before Playwright's [web-first assertions](https://playwright.dev/docs/test-assertions) were a thing. So nowadays you should try to replicate your assertion with them and if its not available use [expect.poll](https://playwright.dev/docs/test-assertions#expectpoll). Then usually this library is not needed anymore.

**Comment by williamlabrum** [comment]
Thanks for the clarification @mxschmitt . Appreciate your time. closing this out.
