### ISSUE TITLE
toEqualValue does not retry, fails instantly

### ISSUE THREAD

**Issue by flaurida** [playwright-community/expect-playwright#19]
Hi there,

I am trying to use `toEqualValue`, and noticed that it does not wait for the condition to be true as I would have expected.

Below is an example where it checks the value of an input. Since the value is not `Playwright`, the test fails instantly. I would have expected it to keep checking the input value before timing out, as sometimes inputs can be filled in with a delay. The error message is `'Playwright' does not equal ''.`

```js
const qawolf = require("qawolf");
const selectors = require("./selectors/myTest.json");

let browser;
let page;

beforeAll(async () => {
  browser = await qawolf.launch();
  const context = await browser.newContext();
  await qawolf.register(context);
  page = await context.newPage();
});

afterAll(async () => {
  await qawolf.stopVideos();
  await browser.close();
});

test("myTest", async () => {
  await page.goto("http://todomvc.com/examples/react");
  await page.click(selectors["0_what_needs_to_b_input"]);
  await page.type(selectors["1_what_needs_to_b_input"], "enter todo");
  await page.press(selectors["2_what_needs_to_b_input"], "Enter");

  const element = await page.$(selectors["2_what_needs_to_b_input"]);
  await expect(element).toEqualValue("Playwright");
});
```

Another note - the README still says 1 second. Just wanted to see if that was still the actual timeout, or if it is just out of date.

Thanks in advance :)

**Comment by mxschmitt** [comment]
Hey @flaurida,
currently I'm just getting the value of the element via `$eval` and then I'm making there a `.textContent` to get the actual text inside of the element.

This unfortunately until now, does not work, if the value of the element changes to the expected one after a few seconds e.g.

Not sure how we should proceed there, definitely a case which we should handle somehow. Playwright internally with the text selector engine is doing a pretty similar thing.

**Comment by flaurida** [comment]
Hi @mxschmitt 😊 thanks for getting back to me! I understand the issue now.

For what it's worth, the API I would advocate for would look something like this, consistent with the `toHaveText` API:

```js
await expect(page).toEqualValue("#my-selector", "Playwright")
```

or 

```js
await expect("#my-selector").toEqualValue("Playwright")
```

I would then expect it to keep retrying the assertion until timeout. 

Let me know your thoughts, happy to collaborate here!

**Comment by mxschmitt** [comment]
Hey,

probably the first case, because the selector has to have access to the page object.

Would be awesome if you want to implement that. Looking forward to it!

**Comment by mxschmitt** [comment]
Closed since it was stale, please reopen if its still an issue.
