### ISSUE TITLE
type definitions from an editor

### ISSUE THREAD

**Issue by banyan** [playwright-community/expect-playwright#20]
![2020-05-04 01 59 48](https://user-images.githubusercontent.com/19625/80920456-fe61cb00-8daa-11ea-89e6-65c64f220821.gif)

Although this seems to be a common problem when extending expect in jest, the editor can't find the type definition. (the test itself works since `setupFilesAfterEnv` is specified)
Explicitly `import "expect-playwright"` in the file works well, but do you know the other way? 

To reproduce: 

```
git clone -b repro-expect-playwright https://github.com/banyan/issue-repro.git
cd issue-repro
yarn
code .qawolf/myTest.test.ts # using vscode
```

**Comment by mxschmitt** [comment]
Hey, there are types :)

You can use them at the top of your file e.g. via 

```typescript
/// <reference types="jest-playwright-preset" />
/// <reference types="expect-playwright" />
```

or at your central tsconfig.json either via files:

```json
{
  "files": [
    "./global.d.ts",
    "node_modules/jest-playwright-preset/types/global.d.ts",
    "node_modules/expect-playwright/global.d.ts"
  ]
}
```
or via types:

```json
{
  "compilerOptions": {
    "types": ["jest-playwright-preset", "expect-playwright"]
  }
}
```

not sure what the most elegant way is, probably types.

**Comment by banyan** [comment]
Thanks! The topmost reference works well, but other ways of going through files or types in tsconfig.json did not on my end.
