### ISSUE TITLE
PageWaitForSelectorOptions incorrectly contains waitFor

### ISSUE THREAD

**Issue by thernstig** [playwright-community/expect-playwright#23]
The option `waitFor` has changed to `state` as part of the Playwright 1.0 release, so this needs to change as well.

````typescript
interface PageWaitForSelectorOptions {
  /**
   * Wait for element to become visible (`visible`), hidden (`hidden`), present in dom (`attached`) or not present in dom (`detached`). Defaults to `attached`.
   */
  waitFor?: "attached" | "detached" | "visible" | "hidden";
```

**Comment by mxschmitt** [comment]
This was already fixed in de0f274ad7c55fd7b4838f0131da3d716f134529 and should be available in 0.2.4: https://cdn.jsdelivr.net/npm/expect-playwright@0.2.4/global.d.ts
