### ISSUE TITLE
Negative (`.not`) assertion timeout defaults to 30 seconds

### ISSUE THREAD

**Issue by jhildenbiddle** [playwright-community/expect-playwright#24]
According to the docs helper methods like`toHaveSelector`, `toHaveText`, `toEqualText`, and `toEqualValue` have a default timeout of 1 second. 

> It has a default timeout of 1 second, which you can overwrite via the options.

This is working as expected for positive assertions:

```js
// Immediate (working)
await expect(page).toHaveSelector('#foo');
```

But negative assertions are defaulting to a 30 second timeout:

```js
// 30 second timeout (not working)
await expect(page).not.toHaveSelector('#foo');
```

I can fix this by manually setting the timeout in `options`, but it would be nice to not have to do this:

```js
// Immediate (manual fix)
await expect(page).not.toHaveSelector('#foo', { timeout: 1 });
```

Configuration:

* jest: 26.1.0
* jest-playwright-preset: 1.2.1
* playwright: 1.2.0

Thanks!

**Comment by mxschmitt** [comment]
Hi!
I'll tomorrow make a new release and address this, thanks for creating this detailed issue 👍

**Comment by mxschmitt** [comment]
Hi, sorry for the delay!

Unfortunately we decided internally that it's not that useful to have a default timeout of 1 second because we would then have this 1 second for all matchers. Not only the not selectors.

**Comment by jhildenbiddle** [comment]
No worries, @mxschmitt. Really appreciate the quick turnaround!
