### ISSUE TITLE
toEqualText() should support empty string

### ISSUE THREAD

**Issue by jhildenbiddle** [playwright-community/expect-playwright#29]
Given the following HTML:

```html
<p></p>
```

The following `toEqualText()` call will timeout:

```js
await expect(page).toEqualText('p', '');
```

The workaround is easy enough:

```js
expect(await page.innerText('p')).toBe('');
```

But it feels out of place when testing multiple elements using `toEqualText()`:

```js
await expect(page).toEqualText('.foo', 'foo');
await expect(page).toEqualText('.bar', 'bar');
await expect(page).toEqualText('.baz', 'baz');
expect(await page.innerText('.empty')).toBe('');
```

Ideally, `toEqualText()` would support an empty string as a valid text match.

**Comment by mxschmitt** [comment]
@jhildenbiddle good one! Definitely sounds like a bug. I hope to fix it during the weekend.

**Comment by mxschmitt** [comment]
@jhildenbiddle not sure how we should handle, since it currently fails that element does not fulfil the actionability factors of Playwright (visible) and throws then the following error: ` waiting for selector "#foobar" to be visible`

Minimal reproducible: https://try.playwright.tech/?s=3gb61an

```
// @ts-check
const playwright = require("playwright");
(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.setContent(`<div id="foobar"></div>`)
  await page.waitForSelector("#foobar");
  await browser.close();
})();
```

**Comment by jhildenbiddle** [comment]
@mxschmitt --

I haven't looked at the source for `toEqualText()`, but would this not be a combination of `page.waitForSelector()` as `attached` and `page.innerText().toBe('')`? `toEqualText()` waits for `waitForSelector()` first, then checks `innerText()`, and any error reported by `toEqualText` specifies which one failed (i.e. failed selector match vs found selector but failed text match).

**Comment by mmarkelov** [comment]
Some investigation on it. According to [docs](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=framewaitforselectorselector-options) **waitForSelector** will return only non-empty element, so because of it you got this kind of errors. I just made #29 where you can find possible workarounds. So maybe we should give ability to search for empty elements?

**Comment by jhildenbiddle** [comment]
@mxschmitt inadvertently answered my question...

> According to docs waitForSelector will return only non-empty element...

This is because the default `state` option value is `visible`, which requires an element to have a "non-empty bounding box and no `visibility:hidden`". Changing this value to `attached` requires only that an element is present in the DOM.

Fortunately, `toEqualText` allows setting `waitForSelector` options. This makes the fix pretty easy.

Given the following HTML:

```html
<p></p>
```

This will timeout (because `state` is `visible` by default):

```js
await expect(page).toEqualText('p', '');
```

This works as expected:

```js
await expect(page).toEqualText('p', '', { state: 'attached' });
```

:facepalm:

Thanks for the feedback though. Much appreciated!
