### ISSUE TITLE
[Feature request] Add `toHaveCount`, assertion for count of elements

### ISSUE THREAD

**Issue by aha-oretama** [playwright-community/expect-playwright#30]
I need new assertion checking the count of elements which the selector matches.
It's very useful to verify the count of elements.

```js
      // before
      await page.waitForSelector(selector);
      const count = await page.$$eval(selector, (el) => el.length);
      expect(count).toBe(1);

      // after
      await expect(page).toHaveCount(selector, 1)
```

It might be better to consider if the new assertion can verify the greater or less count.
```js
await expect(page).toHaveCount(selector, '> 1')
await expect(page).toHaveGreaterThanCount(selector, 1)
```

**Comment by mxschmitt** [comment]
Sounds useful!

**Comment by akapitoha** [comment]
I have a chat app and such an assertion would be very helpful

**Comment by mmarkelov** [comment]
Should be released in new version. @mxschmitt could you please publish new one. I just don't have access to do it

**Comment by mxschmitt** [comment]
Published 0.3.0 👍

**Comment by tarun1122** [comment]
I didn't see the above request implemented here: https://playwright.dev/docs/test-assertions#locator-assertions-to-have-count

await expect(this.questions).toHaveCount(1)

I want to validate if my list count is greater than 1.
How can I achieve this?

@mmarkelov @mxschmitt

**Comment by mskelton** [comment]
@tarun1122 Not sure, but this might work:

```js
await expect(this.questions).not.toHaveCount(0)
await expect(this.questions).not.toHaveCount(1)
```

As a side note, your question should probably be opened as an issue in the [Playwright](https://github.com/microsoft/playwright) repo.

**Comment by tarun1122** [comment]
@mskelton Actually my list is dynamic. Sometimes it gives 2 questions sometimes 5+. I just need to ensure that my list always has atleast 1 question and hence, I want to check the list count is greater than 1.

**Comment by mskelton** [comment]
Right, if you verify the count is not 0 and not 1, that then ensures there is at least two elements.

**Comment by douglaslb** [comment]
I have the same problem... I would like to write a test for a dynamic list, so sometimes my list has 5 elements, or more than 20... is there a way to test this?

**Comment by simon04** [comment]
@douglaslb, you might want to use [`locator.count`](https://playwright.dev/docs/api/class-locator#locator-count):

```ts
await expect(await questions.count()).toBeGreaterThan(20);
```
