### ISSUE TITLE
toHaveSelector with .not.

### ISSUE THREAD

**Issue by thernstig** [playwright-community/expect-playwright#32]
The first case below does not work, whilst the second does. What is the implication of using `expect(page).not.toHaveSelector`? I would have thought it would be similar to the second example, but it is not.

```js
// Does not work
await page.click('text=Delete');
await expect(page).not.toHaveSelector(selector); 
```

```js
// Works
await page.click('text=Delete');
await expect(page).toHaveSelector(selector, { state: 'detached' }); 
```

**Comment by mxschmitt** [comment]
What do you mean with "does not work"? If you use the not selectors, it internally also tries to wait for the default timeout which is 30 seconds by default. So its recommended to pass there an option array and reduce the timeout to e.g. 5 seconds.

**Comment by thernstig** [comment]
The selector exists at the time when `await expect(page).not.toHaveSelector(selector)` is called in our case. So that check fails.

But I would have expected the addition of the `.not.` to actually wait for 30 seconds for the selector to not exist.

**Comment by thernstig** [comment]
@mxschmitt ?

**Comment by mmarkelov** [comment]
@thernstig I believe this is because html element with defined selector is empty.

This is because the default state option value is visible, which requires an element to have a "non-empty bounding box and no visibility:hidden". Changing this value to **attached** requires only that an element is present in the DOM.

**Comment by thernstig** [comment]
I suppose I misunderstood `.not.`. I expected it to wait till something like `hidden` since the default for a normal `waitForSelector` is `visible`. That is not how it works then, and I am required to do what I do in my second example? (Note I could have replaced the second example with `state: 'hidden'` equally well since it does not matter in my case if it is hidden or detached, I just don't care for it to be seen at all.)

**Comment by mmarkelov** [comment]
@thernstig I got your point. And I suppose maybe we should redefine default properties of **waitForSelector**, cause it can be a bit confused. @mxschmitt what do you think?

**Comment by thernstig** [comment]
@mxschmitt ?

**Comment by nulladdict** [comment]
I also got confused from docs to have the same expectations as @thernstig described
I'm not sure about redefining properties, but adding something like "use `await expect(page).toHaveSelector(selector, { state: 'hidden' });` to wait for selector to disappear" to the readme seems like a good idea

**Comment by mxschmitt** [comment]
I saw its possible to detect if its not or a normal selector. So we can simply have a timeout of e.g. 1000 by default when its not and otherwise no (playwright default: 30s) timeout: https://jestjs.io/docs/expect#thisisnot

**Comment by nulladdict** [comment]
I feel like having `.not.toHaveSelector(selector)` behave like `.toHaveSelector(selector, { state: 'hidden' })` is a reasonable expectation, since `hidden` is an opposite to default `visible` state ([docs](https://playwright.dev/docs/api/class-page/?_highlight=%27hidden%27#pagewaitforselectorselector-options))

In my experience, changing the timeout doesn't really help, since all the other selectors wait for the desired state, and current `.not` combination acts right away, no matter the timeout

**Comment by avaragado** [comment]
I'd like to add that `toHaveSelectorCount` has a similar issue. It's quite natural to want to say:

```ts
await expect(page).toHaveSelectorCount(selector, 0);
```

For example, when you have a filter input, and simulate typing a filter that results in zero matches. Sadly it doesn't work as expected.

In this example, this works:

```ts
expect(await page.$$(selector)).toHaveLength(0);
```

**Comment by mskelton** [comment]
Just throwing in my two cents, but from my experience `.toHaveSelector(selector, { state: 'detached' })` is desired in nearly all instances.  Waiting for a specific timeout for the element to exist, whether 1 second, 5 seconds, or more makes a very non-ideal situation in tests.  If you use a long timeout you add lots of extra time to tests, if you use a short timeout, your tests become brittle if elements hide as a result of an API call or some other asynchronous operation where there can be differences in how long it takes between test runs.  The use case seems valid if wanting to ensure an element never appears for a period of time, but even then my team uses hidden `div`s in those edge cases where we need to expect an element to not appear when it never was on the page in the first place.
