### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by shahar-h** [playwright-community/expect-playwright#33]
Latest version (0.2.5) depends on playwright-core ^1.2.1: https://github.com/playwright-community/expect-playwright/blob/973c949d123f71de9a43f9e0d1bd107288d9fb1a/package.json#L15
When using latest playwright and jest-playwright there are mismatched versions of playwright-core.
I noticed that master is already updated with playwright-core ^1.5.1 as a peer dependency.

**Comment by mxschmitt** [comment]
Published the new version, you have to install `playwright-core` as a peer dependency now to be in depended: https://github.com/playwright-community/expect-playwright/releases/tag/v0.2.6

**Comment by shahar-h** [comment]
Thanks for the quick response 👍
