### ISSUE TITLE
Option to disable dumping whole page into console

### ISSUE THREAD

**Issue by sjurgis** [playwright-community/expect-playwright#34]
I test multi-megabyte apps and it's huge pain having it dumped into console, sometimes multiple times. I need to scroll tons just to find which test failed.

We should have option to disable that.

**Comment by mmarkelov** [comment]
@sjurgis could you please provide some cases when you got this kind of annoying logs?

**Comment by sjurgis** [comment]
@mmarkelov sorry for the wait, consider this:

```
const {chromium} = require('playwright-chromium');
const expect = require("expect-playwright")
void async function() {
    const browser = await chromium.launch();
    const page = await browser.newPage();
    await page.goto('https://google.com')
    await expect(page).toHaveText('bing.com')
}()
```

```
➜  sfdx git:(3058) ✗ node repro.js
(node:53745) UnhandledPromiseRejectionWarning: Error: 'bing.com' is not included in 'body,html{height:100%;margin:0;padding:0}#viewport{min-height:100%;position:relative;width:100%}.content{padding-bottom:35px}#footer{bottom:0;font-size:10pt;height:105px;width:100%}#gog{pad....
```

This goes on forever...

**Comment by mmarkelov** [comment]
Just looked through this issue. IDK how we should implement this. Some possible ways:
- Add bool argument as the last one. It will be a bit difficult to implement.
```js
await expect(page).toHaveText('bing.com', true)
```
- Add bool param to options.
```js
await expect(page).toHaveText('bing.com', { skipWholeText: true })
```
- Add some param to `process env`. The easiest one.

@mmarkelov your thoughts?

**Comment by mxschmitt** [comment]
I would maybe add something like that if there was no selector passed. Because then it fallbacks to the body which is usually quite long.

**Comment by mmarkelov** [comment]
@mxschmitt that make sense, but I think that there are cases when the selector also can be too long. So maybe we should have some checks for the length of `actualTextContent`?

**Comment by mxschmitt** [comment]
sounds good. But I would determine the length of it in the browers JS runtime instead of Node.js

**Comment by mxschmitt** [comment]
Closed for now as part of the triage, seems solved with the current set of API's and the recent rework of the diff-visualisation.
