### ISSUE TITLE
[Documentation] toHaveSelectorCount matcher

### ISSUE THREAD

**Issue by voodoofrog** [playwright-community/expect-playwright#41]
I just wanted to point out the Readme has not been updated with the toHaveSelectorCount documentation. I'd do it myself but I don't want to presume I 100% know how it works (although I _assume_ it's roughly the same as toHaveSelector but with an additional param for the expected count).

**Comment by mmarkelov** [comment]
@voodoofrog yeah that is almost the same as `toHaveSelector`. You can use it in two ways:
- ```await toHaveSelectorCount(page, ".foobar", 2)```
- ```await toHaveSelectorCount(page, ".foobar", 1, { timeout: 1 * 1000 })```
