### ISSUE TITLE
.not not exposed

### ISSUE THREAD

**Issue by maxime-helen** [playwright-community/expect-playwright#45]
`playwright-core`: `^1.7.1`
`playwright-expect`: `0.3.0`

I am trying following code per [documentation](https://github.com/playwright-community/expect-playwright#tohaveselector)
```
await expect(page).not.toHaveSelector("#foobar", {
  timeout: 1 * 1000
})
```

However I get following error:
```
    TypeError: Cannot read property 'toHaveSelector' of undefined

      11 | 
      12 | export const isWidgetMessageHidden = (page) => {
    > 13 |   return expect(page)
         |          ^
      14 |     .not
      15 |     .toHaveSelector(selectId(REFERRAL.WIDGET_MESSAGE))
      16 | }
```

Logging shows below:
```
console.log(expect(page));

/* returns below, missing not method
    {
      toHaveText: [AsyncFunction: toHaveText],
      toEqualText: [AsyncFunction: toEqualText],
      toHaveSelector: [AsyncFunction: toHaveSelector],
      toEqualValue: [AsyncFunction: toEqualValue]
    }
*/
```

Am I missing something? Many thanks for these great helpers!

**Comment by mmarkelov** [comment]
@maxime-helen seems like that you are using `expect-playwright` without `jest`, so this is expected behaviour.

**Comment by maxime-helen** [comment]
I was importing `expect` straight from test script, called with jest CLI. Configuring my `jest.config.js` instead with `setupFilesAfterEnv: ['expect-playwright']` fixed the problem! Thanks!
