### ISSUE TITLE
toHaveText timeout

### ISSUE THREAD

**Issue by nadavkaner** [playwright-community/expect-playwright#50]
What is the reason that `await expect(page).toHaveText("Playwright")` has a timeout of only a 1 sec? it's a real cumbersome to pass the timeout as a second parameter every time

**Comment by mmarkelov** [comment]
You can't pass options as second param in new version. Actually this is good question, cause for these cases:
```js
await expect(page).toHaveText("Playwright")
```
we just get a `body` content without any waiting, but I'm not sure what should we do for this case.
In my mind there is no much sense to use `waitForSelector` on `body`.
@mxschmitt what do you think?

**Comment by mxschmitt** [comment]
Thats what I mean that we should keep the options parameter for such a case. Would be great to add tests for these cases and then based on them fix the current implementation.

**Comment by nadavkaner** [comment]
Thanks, I just wondering why the default behavior of `toHaveText` is not auto-wait and the user should pass timeout as the second argument? for the other assertions APIs here like `toHaveSelector`, the default behavior is to wait.
