### ISSUE TITLE
(feature request): Adding .toHaveFocus() to the library

### ISSUE THREAD

**Issue by mfrachet** [playwright-community/expect-playwright#61]
Hello folks and thank you for the great work you're doing with the tool! That's amazing 😊 

I'm opening this issue to request for a `.toHaveFocus()` function that will allow to verify what is the actually focused element. This may become very helpful when testing for accessibility.

Actually, to determine if an element has focused on it, I have two options that are quite verbose:

```js
  const axTreeSnapshot = await page.accessibility.snapshot({ root });
  // does not look very consistent on firefox from my experimentation, but I may be wrong
  axTreeSnapshot.focused
```

or as described in https://github.com/microsoft/playwright/issues/2159#issuecomment-625883641 with the following:

```js
const foo1Isfocused = await page.$eval("#foo1", (el) => el === document.activeElement)
```

What do you think?

**Comment by mmarkelov** [comment]
@mfrachet thanks for your suggestion. I think we can move the second option in separate helper`.toHaveFocus()`
That make sense for me.
