### ISSUE TITLE
Feature request: expect(frame: Frame)

### ISSUE THREAD

**Issue by fkranenburg** [playwright-community/expect-playwright#66]
We have a lot of iframes inside our application and would like to test inside the iframe pages. It would be great if `expect` could also work with a Frame object.

**Comment by southpolesteve** [comment]
Same. Would love to see this added.

**Comment by mmarkelov** [comment]
@southpolesteve I just made some improvements to implement this logic. So think that it's ready for merge. 
@mxschmitt could you please check this? 
Thanks!

**Comment by mmarkelov** [comment]
@mxschmitt i suppose that we should publish new version?

**Comment by mxschmitt** [comment]
> @mxschmitt i suppose that we should publish new version?

yup sounds good to me
