### ISSUE TITLE
Improve matcher messages

### ISSUE THREAD

**Issue by mskelton** [playwright-community/expect-playwright#69]
The result messages from the matchers in expect-playwright get the job done by displaying information about what went wrong.  However, Jest has some utils that are available that can make matcher messages more visually friendly as well as consistent with the default matchers built into Jest (e.g. `toBe`).

I've got a WIP branch to show how this could look: https://github.com/mskelton/expect-playwright/tree/improve-matcher-hints

## Before
<img width="657" alt="Screen Shot 2021-05-11 at 10 09 20 AM" src="https://user-images.githubusercontent.com/25914066/117839578-f865bc00-b240-11eb-9021-258b6c83880a.png">

## After

<img width="673" alt="Screen Shot 2021-05-11 at 10 11 26 AM" src="https://user-images.githubusercontent.com/25914066/117839919-4a0e4680-b241-11eb-98d3-7f28d7fa3095.png">

**Comment by mmarkelov** [comment]
@mskelton thank you very much about this! It will be really nice to have! i'll try to look through your branch and i can help you with this if will have any troubles.

**Comment by mskelton** [comment]
@mmarkelov Awesome, I wanted to open this issue to make sure this is a good change you are all good with me making.  Now that I know you are good with it, I'll continue working on my branch to get the matchers updated.
