### ISSUE TITLE
[Question] How do we setup default timeout?

### ISSUE THREAD

**Issue by xuanzhaopeng** [playwright-community/expect-playwright#74]
Hey team,

May I ask how could we setup default timeout? as document said it's 30 seconds, but I don't find where we set it. Is it possible to set it from jest config also?

Thanks

**Comment by mxschmitt** [comment]
Hi, expect-playwright has no internal timeout handling, it will use the Playwright timeout by default. See here how to reduce or increase it: https://playwright.dev/docs/api/class-page#pagesetdefaulttimeouttimeout
