### ISSUE TITLE
Support for @playwright/test

### ISSUE THREAD

**Issue by krokofant** [playwright-community/expect-playwright#82]
Does this work with the @playwright/test package?

Can't seem to follow the instructions for the Playwright test runner.

Version 0.4.0 is installed.

![image](https://user-images.githubusercontent.com/5908498/121401253-cd15e000-c958-11eb-9a60-5da840c5c61c.png)

**Comment by mskelton** [comment]
Ah yes, we missed exporting that type.  I should have a PR out later today to fix.

**Comment by mxschmitt** [comment]
Version 0.4.1 should fix it.
