### ISSUE TITLE
expect() should accept Frame argument.

### ISSUE THREAD

**Issue by xpol** [playwright-community/expect-playwright#85]
Given `frame = await handle.contentFrame()`.
When I need both `expect(handle).toEqualText()` and `expect(frame.isEnabled()).toBeTruthy()`
Then it is not clear that the `handle` and `frame` are refering to the "same" iframe:

```js
await expect(handle).toEqualText('#completeButton', 'Submit')
expect(await frame.isEnabled('#completeButton')).toBeTruthy()
```

With support Frame argument, it should be much clear:

```js
await expect(frame).toEqualText('#completeButton', 'Submit')
expect(await frame.isEnabled('#completeButton')).toBeTruthy()
```

**Comment by mskelton** [comment]
Should be doable, just need to update `getElementText` to also detect frames.
